name: Build & deploy documentation to GitHub Pages

on:
  push:
    branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # create mdbook
      - name: Install mdBook
        run: cargo install mdbook
      - name: Test Docs
        run: mdbook test
        working-directory: docs
      - name: Build Docs
        run: mdbook build
        working-directory: docs
      # create source docs
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
      - name: Create documentation
        run: cargo doc
      - name: Copy documentation into book structure
        run: cp -r target/thumbv7em-none-eabihf/doc/ docs/book/src-doc/
      # publish
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the book
          path: 'docs/book/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
